DROP TABLE IF EXISTS url_checks;

DROP TABLE IF EXISTS urls;

CREATE TABLE  urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMP );


CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    status_code INT,
    title TEXT,
    h1 TEXT,
    description TEXT,
    url_id BIGINT,

    CONSTRAINT fk_url_checks_url_id
    FOREIGN KEY (url_id)
    REFERENCES urls(id)
    ON DELETE CASCADE

);